import { KeyboardRow } from './types';

export type Difficulty = 'easy' | 'medium' | 'hard';

export const PRACTICE_PARAGRAPHS: Record<Difficulty, string[]> = {
  easy: [
    'adam reads a calm story as sara writes a clean line',
    'mira and sam share simple words across a quiet class',
    'a little river runs near a green hill and a calm area',
    'small steps make steady skill as fingers learn smooth motion',
    'nina sees clear stars and smiles as a soft rain falls',
    'a wise teacher asks each learner to keep a safe pace',
    'the class reads easy lines and repeats each phrase again',
    'simple practice builds strong habits and keeps errors lower',
    'a short session each day can raise speed over time',
    'slow starts are fine as long as focus stays steady',
    'larry likes clear goals and tracks each small gain daily',
    'a bright room and a calm mind help smooth typing flow',
    'mason and alice train daily and share useful learning tips',
    'a steady hand and clear eyes guide each letter well',
    'every learner can improve with patient and regular practice',
    'timely breaks keep hands safe and minds fresh for work',
    'a clean desk and clear plan support focused practice',
    'sara reads a line and then writes the same line again',
    'careful effort grows skill as each session adds progress',
    'small wins each day create large growth over many weeks',
    'a learner with calm focus can type with solid rhythm',
  ],
  medium: [
    'Alice reads clear lines, and Sam checks each word carefully.',
    'A simple class asks: can steady practice reduce small errors?',
    'Mira writes fast, but she pauses; then she checks each phrase.',
    'Quiet focus helps speed, while careful review keeps quality high.',
    'A smart routine includes short breaks, clean posture, and calm breath.',
    'Can Sarah type this phrase, then fix each mistake quickly?',
    'Daily practice grows skill; weekly review keeps progress visible.',
    'A clear plan says: start slow, stay steady, and finish strong.',
    'When focus drops, take a pause; then return with fresh attention.',
    'Mark each error, note the symbol, and train that pattern again.',
    'Simple lines become smooth when timing, rhythm, and accuracy align.',
    'A careful learner asks, "Which keys cause slips most often?"',
    'Write each line with intent, then measure speed and quality.',
    'Strong habits form slowly; consistent reps make them reliable.',
    'Can Alex keep clean spacing, proper commas, and steady pace?',
    'A useful session tracks errors, speed, and focused repetition.',
    'Practice can be short, but quality must stay very high.',
    'Each line should feel controlled, clear, and confidently typed.',
    'A patient typist improves faster than a rushed and careless one.',
    'Good rhythm, clear sight, and stable hands build stronger output.',
    'Repeat this plan: focus first, speed second, then review.',
  ],
  hard: [
    'A STRONG typist asks: can speed stay SHARP, precise, and calm?',
    'While SAM scans errors, Alice writes: "Check commas, periods, and quotes."',
    'Practice DAILY; review WEEKLY; improve steadily, even under pressure.',
    'Can a FAST learner keep ACCURACY high, or does haste create slips?',
    'When focus fades, pause briefly: breathe, reset, and continue typing.',
    'A CLASSIC rule says, "Quality first; speed follows with repetition."',
    'Track each miss: letters, commas, periods, colons, semicolons, quotes, and question marks.',
    'Sharp rhythm, CLEAN spacing, and clear intent produce better output.',
    'Can SARAH type this line quickly, then correct each tiny error?',
    'A stable routine includes posture checks, timed reps, and careful review.',
    'Write with control; avoid random bursts that reduce precision.',
    'A HARD drill asks: "Can you hold speed while symbols appear often?"',
    'Use focused sets, then raise difficulty as confidence grows.',
    'Small gains compound: DAILY practice creates MAJOR long-term progress.',
    'When mistakes repeat, isolate that pattern; train it again and again.',
    'Can ALEX keep CAPS steady, symbols clean, and rhythm smooth?',
    'A precise typist notices details: spacing, punctuation, and letter case.',
    "Check this phrase: \"Is every ; : , . \\\" ' and ? exactly right?\"",
    'Rapid typing is useful, but reliable output is the true goal.',
    'Build discipline first; advanced speed comes after consistent control.',
    'A final test asks: can you stay accurate through long sessions?',
  ],
};

export const KEYBOARD_LAYOUT: KeyboardRow[] = [
  {
    keys: [
      { label: '`', secondary: '~', code: 'Backquote' },
      { label: '1', secondary: '!', code: 'Digit1' },
      { label: '2', secondary: '@', code: 'Digit2' },
      { label: '3', secondary: '#', code: 'Digit3' },
      { label: '4', secondary: '$', code: 'Digit4' },
      { label: '5', secondary: '%', code: 'Digit5' },
      { label: '6', secondary: '^', code: 'Digit6' },
      { label: '7', secondary: '&', code: 'Digit7' },
      { label: '8', secondary: '*', code: 'Digit8' },
      { label: '9', secondary: '(', code: 'Digit9' },
      { label: '0', secondary: ')', code: 'Digit0' },
      { label: '-', secondary: '_', code: 'Minus' },
      { label: '=', secondary: '+', code: 'Equal' },
      { label: 'Backspace', code: 'Backspace', width: 'w-20' },
    ],
  },
  {
    keys: [
      { label: 'Tab', code: 'Tab', width: 'w-14' },
      { label: 'Q', code: 'KeyQ' },
      { label: 'W', code: 'KeyW' },
      { label: 'E', code: 'KeyE' },
      { label: 'R', code: 'KeyR' },
      { label: 'T', code: 'KeyT' },
      { label: 'Y', code: 'KeyY' },
      { label: 'U', code: 'KeyU' },
      { label: 'I', code: 'KeyI' },
      { label: 'O', code: 'KeyO' },
      { label: 'P', code: 'KeyP' },
      { label: '[', secondary: '{', code: 'BracketLeft' },
      { label: ']', secondary: '}', code: 'BracketRight' },
      { label: '\\', secondary: '|', code: 'Backslash', width: 'w-14' },
    ],
  },
  {
    keys: [
      { label: 'Caps Lock', code: 'CapsLock', width: 'w-16' },
      { label: 'A', code: 'KeyA' },
      { label: 'S', code: 'KeyS' },
      { label: 'D', code: 'KeyD' },
      { label: 'F', code: 'KeyF' },
      { label: 'G', code: 'KeyG' },
      { label: 'H', code: 'KeyH' },
      { label: 'J', code: 'KeyJ' },
      { label: 'K', code: 'KeyK' },
      { label: 'L', code: 'KeyL' },
      { label: ';', secondary: ':', code: 'Semicolon' },
      { label: "'", secondary: '"', code: 'Quote' },
      { label: 'Enter', code: 'Enter', width: 'w-20' },
    ],
  },
  {
    keys: [
      { label: 'Shift', code: 'ShiftLeft', width: 'w-24' },
      { label: 'Z', code: 'KeyZ' },
      { label: 'X', code: 'KeyX' },
      { label: 'C', code: 'KeyC' },
      { label: 'V', code: 'KeyV' },
      { label: 'B', code: 'KeyB' },
      { label: 'N', code: 'KeyN' },
      { label: 'M', code: 'KeyM' },
      { label: ',', secondary: '<', code: 'Comma' },
      { label: '.', secondary: '>', code: 'Period' },
      { label: '/', secondary: '?', code: 'Slash' },
      { label: 'Shift', code: 'ShiftRight', width: 'w-24' },
    ],
  },
  {
    keys: [{ label: 'Space', code: 'Space', width: 'w-96' }],
  },
];
